### ISSUE TITLE
java -jar 无法运行 java版本8,11,14 均无法运行

### ISSUE THREAD

**Issue by Po3son** [zangcc/Aazhen-v3.1#1]
java -jar 无法运行 java版本8,11,14 均无法运行

**Comment by zangcc** [comment]
感谢反馈！
我是用最新的java17开发的，版本不兼容的问题我确实没有考虑到。现在我已经把工具重做了，因为工作原因所以开发速度比较慢，大概月底会发布一个全新的漏扫工具，不止于thinkphp的漏洞扫描。版本问题我会顺便解决一下，再次感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 晚上7:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zangcc/ThinkphpGUI-2.0] java -jar 无法运行 java版本8,11,14 均无法运行 (Issue #1)




 
java -jar 无法运行 java版本8,11,14 均无法运行

**Comment by zangcc** [comment]
> java -jar 无法运行 java版本8,11,14 均无法运行

你好，答应的月底重做已经完成，我重新用jdk-1.8重写了，现在exe文件可以轻松执行。
